// Mock data for the Agricultural Supervisor App
import { Field, Labour, Vehicle, Task, FieldVisit, Request, ReportingOfficer, User } from '../types';

export const mockUser: User = {
  id: '1',
  supervisorId: 'SUP001',
  name: 'John Smith',
  role: 'Field Supervisor',
  phone: '+1 234-567-8901',
  email: 'john.smith@agrifarm.com',
  assignedFields: ['F001', 'F002', 'F003'],
};

export const mockCredentials = {
  supervisorId: 'SUP001',
  password: 'admin123',
};

export const reportingOfficer: ReportingOfficer = {
  id: 'RO001',
  name: 'Michael Johnson',
  designation: 'Regional Manager',
  phone: '+1 234-567-8900',
  email: 'michael.johnson@agrifarm.com',
};

export const mockFields: Field[] = [
  {
    id: 'F001',
    name: 'North Valley Field',
    area: '25 acres',
    crop: 'Wheat',
    status: 'Active',
    location: { latitude: 37.7749, longitude: -122.4194 },
  },
  {
    id: 'F002',
    name: 'East Ridge Farm',
    area: '40 acres',
    crop: 'Corn',
    status: 'Active',
    location: { latitude: 37.7849, longitude: -122.4094 },
  },
  {
    id: 'F003',
    name: 'South Meadow',
    area: '18 acres',
    crop: 'Soybeans',
    status: 'Preparing',
    location: { latitude: 37.7649, longitude: -122.4294 },
  },
  {
    id: 'F004',
    name: 'West Hills',
    area: '32 acres',
    crop: 'Rice',
    status: 'Active',
    location: { latitude: 37.7949, longitude: -122.4394 },
  },
  {
    id: 'F005',
    name: 'Central Plains',
    area: '50 acres',
    crop: 'Cotton',
    status: 'Harvesting',
    location: { latitude: 37.7549, longitude: -122.4094 },
  },
];

export const mockLabour: Labour[] = [
  {
    id: 'L001',
    name: 'Carlos Rodriguez',
    role: 'Field Worker',
    phone: '+1 234-567-8910',
    status: 'Active',
    assignedField: 'F001',
    joinDate: '2023-01-15',
  },
  {
    id: 'L002',
    name: 'Maria Garcia',
    role: 'Irrigation Specialist',
    phone: '+1 234-567-8911',
    status: 'Active',
    assignedField: 'F002',
    joinDate: '2023-02-20',
  },
  {
    id: 'L003',
    name: 'James Wilson',
    role: 'Equipment Operator',
    phone: '+1 234-567-8912',
    status: 'Active',
    assignedField: 'F001',
    joinDate: '2022-11-10',
  },
  {
    id: 'L004',
    name: 'Sophia Martinez',
    role: 'Field Worker',
    phone: '+1 234-567-8913',
    status: 'On Leave',
    assignedField: 'F003',
    joinDate: '2023-03-05',
  },
  {
    id: 'L005',
    name: 'Robert Brown',
    role: 'Harvester',
    phone: '+1 234-567-8914',
    status: 'Active',
    assignedField: 'F002',
    joinDate: '2022-09-12',
  },
  {
    id: 'L006',
    name: 'Jennifer Davis',
    role: 'Quality Inspector',
    phone: '+1 234-567-8915',
    status: 'Active',
    assignedField: 'F004',
    joinDate: '2023-04-18',
  },
  {
    id: 'L007',
    name: 'David Anderson',
    role: 'Field Worker',
    phone: '+1 234-567-8916',
    status: 'Inactive',
    assignedField: 'F001',
    joinDate: '2022-07-25',
  },
  {
    id: 'L008',
    name: 'Linda Thompson',
    role: 'Pesticide Applicator',
    phone: '+1 234-567-8917',
    status: 'Active',
    assignedField: 'F003',
    joinDate: '2023-01-30',
  },
];

export const mockVehicles: Vehicle[] = [
  {
    id: 'V001',
    type: 'Tractor',
    registrationNumber: 'TRC-2301',
    driver: 'James Wilson',
    status: 'In Use',
    location: 'North Valley Field',
    fuelLevel: 75,
  },
  {
    id: 'V002',
    type: 'Harvester',
    registrationNumber: 'HRV-2302',
    driver: 'Robert Brown',
    status: 'Available',
    location: 'Equipment Shed',
    fuelLevel: 90,
  },
  {
    id: 'V003',
    type: 'Sprayer',
    registrationNumber: 'SPR-2303',
    driver: 'Linda Thompson',
    status: 'In Use',
    location: 'South Meadow',
    fuelLevel: 45,
  },
  {
    id: 'V004',
    type: 'Truck',
    registrationNumber: 'TRK-2304',
    driver: 'David Anderson',
    status: 'Maintenance',
    location: 'Service Center',
    fuelLevel: 30,
  },
  {
    id: 'V005',
    type: 'Tractor',
    registrationNumber: 'TRC-2305',
    driver: 'Carlos Rodriguez',
    status: 'Available',
    location: 'Equipment Shed',
    fuelLevel: 85,
  },
  {
    id: 'V006',
    type: 'Pickup Truck',
    registrationNumber: 'PKP-2306',
    driver: 'Unassigned',
    status: 'Available',
    location: 'Main Office',
    fuelLevel: 60,
  },
];

export const mockTasks: Task[] = [
  {
    id: 'T001',
    title: 'Soil Preparation for Spring Planting',
    description: 'Complete soil testing and prepare fields for spring planting season. Include fertilizer application.',
    type: 'Cultivation',
    priority: 'High',
    status: 'In Progress',
    assignedField: 'F003',
    assignedTo: 'Carlos Rodriguez',
    startDate: '2026-02-01',
    dueDate: '2026-02-15',
    progress: 60,
  },
  {
    id: 'T002',
    title: 'Irrigation System Maintenance',
    description: 'Check and repair all irrigation lines in East Ridge Farm. Replace broken sprinklers.',
    type: 'Cultivation',
    priority: 'Medium',
    status: 'Pending',
    assignedField: 'F002',
    assignedTo: 'Maria Garcia',
    startDate: '2026-02-10',
    dueDate: '2026-02-20',
    progress: 0,
  },
  {
    id: 'T003',
    title: 'Equipment Transport to North Valley',
    description: 'Transport harvester and two tractors to North Valley Field for upcoming harvest.',
    type: 'Driver',
    priority: 'High',
    status: 'Pending',
    assignedField: 'F001',
    assignedTo: 'James Wilson',
    startDate: '2026-02-08',
    dueDate: '2026-02-09',
    progress: 0,
  },
  {
    id: 'T004',
    title: 'Pest Control Application',
    description: 'Apply approved pesticides to control recent aphid infestation in wheat fields.',
    type: 'Cultivation',
    priority: 'High',
    status: 'In Progress',
    assignedField: 'F001',
    assignedTo: 'Linda Thompson',
    startDate: '2026-02-05',
    dueDate: '2026-02-08',
    progress: 45,
  },
  {
    id: 'T005',
    title: 'Contract Labor for Harvesting',
    description: 'Coordinate with contract labor team for cotton harvesting operations.',
    type: 'Contract',
    priority: 'Medium',
    status: 'Pending',
    assignedField: 'F005',
    assignedTo: 'Robert Brown',
    startDate: '2026-02-15',
    dueDate: '2026-03-01',
    progress: 0,
  },
  {
    id: 'T006',
    title: 'Weekly Quality Inspection',
    description: 'Conduct weekly crop quality inspection and document findings.',
    type: 'Cultivation',
    priority: 'Low',
    status: 'Completed',
    assignedField: 'F004',
    assignedTo: 'Jennifer Davis',
    startDate: '2026-02-01',
    dueDate: '2026-02-05',
    progress: 100,
  },
  {
    id: 'T007',
    title: 'Fence Repair - South Boundary',
    description: 'Repair damaged fencing along the south boundary of the property.',
    type: 'Other',
    priority: 'Low',
    status: 'Pending',
    assignedField: 'F003',
    assignedTo: 'David Anderson',
    startDate: '2026-02-12',
    dueDate: '2026-02-18',
    progress: 0,
  },
];

export const mockFieldVisits: FieldVisit[] = [
  {
    id: 'FV001',
    fieldId: 'F001',
    fieldName: 'North Valley Field',
    date: '2026-02-10',
    time: '09:00 AM',
    status: 'Pending',
  },
  {
    id: 'FV002',
    fieldId: 'F003',
    fieldName: 'South Meadow',
    date: '2026-02-08',
    time: '02:00 PM',
    status: 'Pending',
  },
  {
    id: 'FV003',
    fieldId: 'F002',
    fieldName: 'East Ridge Farm',
    date: '2026-02-05',
    time: '10:30 AM',
    status: 'Completed',
    cropCondition: 'Good',
    observations: 'Corn crops are showing healthy growth. Irrigation system working efficiently. Some minor weed growth noticed in the eastern section.',
    recommendations: 'Continue current watering schedule. Plan for weed control in the next week. Monitor for any signs of pests.',
    issues: ['Minor weed growth in eastern section', 'One irrigation sprinkler needs adjustment'],
    photos: [],
    location: { latitude: 37.7849, longitude: -122.4094 },
  },
  {
    id: 'FV004',
    fieldId: 'F001',
    fieldName: 'North Valley Field',
    date: '2026-02-04',
    time: '08:00 AM',
    status: 'Completed',
    cropCondition: 'Fair',
    observations: 'Wheat showing signs of aphid infestation in the northern section. Overall crop health is moderate. Soil moisture levels are adequate.',
    recommendations: 'Immediate pest control treatment required. Increase monitoring frequency. Consider additional fertilizer application in 2 weeks.',
    issues: ['Aphid infestation in northern section', 'Some yellowing of leaves observed'],
    photos: [],
    location: { latitude: 37.7749, longitude: -122.4194 },
  },
  {
    id: 'FV005',
    fieldId: 'F004',
    fieldName: 'West Hills',
    date: '2026-02-03',
    time: '01:00 PM',
    status: 'Completed',
    cropCondition: 'Excellent',
    observations: 'Rice paddies are in excellent condition. Water levels are optimal. No signs of disease or pest activity. Growth rate is ahead of schedule.',
    recommendations: 'Maintain current management practices. Schedule harvest planning meeting. Prepare storage facilities.',
    issues: [],
    photos: [],
    location: { latitude: 37.7949, longitude: -122.4394 },
  },
  {
    id: 'FV006',
    fieldId: 'F005',
    fieldName: 'Central Plains',
    date: '2026-02-12',
    time: '11:00 AM',
    status: 'Pending',
  },
  {
    id: 'FV007',
    fieldId: 'F002',
    fieldName: 'East Ridge Farm',
    date: '2026-02-15',
    time: '03:30 PM',
    status: 'Pending',
  },
];

export const mockRequests: Request[] = [
  {
    id: 'REQ001',
    title: 'Additional Irrigation Equipment',
    category: 'Equipment',
    priority: 'High',
    status: 'Pending',
    description: 'Need 5 additional sprinkler heads and 200 feet of irrigation pipe for East Ridge Farm expansion.',
    relatedField: 'F002',
    photos: [],
    submittedDate: '2026-02-05',
  },
  {
    id: 'REQ002',
    title: 'Tractor Maintenance Service',
    category: 'Maintenance',
    priority: 'High',
    status: 'Approved',
    description: 'TRC-2301 requires regular maintenance service. Engine making unusual noise. Due for oil change and filter replacement.',
    relatedField: 'F001',
    photos: [],
    submittedDate: '2026-02-03',
    response: 'Approved. Service scheduled for Feb 8th. Replacement tractor will be provided.',
  },
  {
    id: 'REQ003',
    title: 'Additional Field Workers',
    category: 'Personnel',
    priority: 'Medium',
    status: 'Pending',
    description: 'Request 3 additional field workers for upcoming harvest season in Central Plains.',
    relatedField: 'F005',
    photos: [],
    submittedDate: '2026-02-04',
  },
  {
    id: 'REQ004',
    title: 'Fertilizer Supply',
    category: 'Resource',
    priority: 'Medium',
    status: 'Approved',
    description: 'Need 500 kg of NPK fertilizer for South Meadow soil preparation.',
    relatedField: 'F003',
    photos: [],
    submittedDate: '2026-02-01',
    response: 'Approved. Delivery scheduled for Feb 7th.',
  },
  {
    id: 'REQ005',
    title: 'Pesticide Stock Replenishment',
    category: 'Resource',
    priority: 'High',
    status: 'Approved',
    description: 'Urgent request for aphid control pesticide. Current stock running low.',
    relatedField: 'F001',
    photos: [],
    submittedDate: '2026-02-05',
    response: 'Approved. Emergency delivery arranged for Feb 6th.',
  },
  {
    id: 'REQ006',
    title: 'Replace Broken Water Pump',
    category: 'Equipment',
    priority: 'Low',
    status: 'Rejected',
    description: 'Request for new water pump for backup irrigation system.',
    relatedField: 'F004',
    photos: [],
    submittedDate: '2026-01-28',
    response: 'Rejected. Current pump can be repaired. Maintenance team will handle.',
  },
];

export const getActiveLabourCount = () => mockLabour.filter(l => l.status === 'Active').length;
export const getActiveVehiclesCount = () => mockVehicles.filter(v => v.status === 'In Use').length;
export const getTotalArea = () => {
  const total = mockFields.reduce((sum, field) => {
    const area = parseInt(field.area);
    return sum + area;
  }, 0);
  return `${total} acres`;
};
export const getPendingVisitsCount = () => mockFieldVisits.filter(v => v.status === 'Pending').length;
export const getCompletedVisitsToday = () => {
  const today = new Date().toISOString().split('T')[0];
  return mockFieldVisits.filter(v => v.status === 'Completed' && v.date === today).length;
};
